// Seeded Data for Clow Cards

const cards = [
    {
      id: 1,
      title: 'the dark',
      category: 'dark',
      guardian: 'Yue - Moon',
      img: 'https://i.imgur.com/yTJgibz.jpeg',
      desc: `The Dark (Kanji: 闇, Katakana: ダーク, Romanji: Dāku) is a Clow Card with the power to control darkness. Alongside The Light, it is one of the foremost of the Clow Cards, and falls under the power of the Moon, Yue and Eastern Magic. `,
    },
    {
      id: 2,
      title: 'the light',
      category: 'light',
      guardian: 'Kero - Sun',
      img: 'https://i.imgur.com/Jut3y6l.jpeg',
      desc: `The Light (Kanji: 光, Katakana: ライト, Romanji: Raito) is a Clow Cards with the power to control light. Alongside The Dark, it is one of the foremost of the Clow Cards, and falls under the power of the Sun, Cerberus, and Western Magic.`,
    },
    {
      id: 3,
      title: 'the watery',
      category: 'water',
      guardian: 'Yue - Moon',
      img: 'https://i.imgur.com/t6xNpAx.jpeg',
      desc: `The Watery (Kanji: 水, Katakana: ウォータリー, Romanji: Uōtarī) is a Clow Card with the power to manipulate and control water. It is one of the four elemental cards, and as such it is one of the most powerful. Watery falls under the power of the Moon, Yue and under Eastern Magic.`,
    },
    {
      id: 4,
      title: 'the firey',
      category: 'fire',
      guardian: 'Kero - Sun',
      img: 'https://i.imgur.com/uwTRmqf.jpeg',
      desc: `The Firey (Kanji: 火, Katakana: ファイーリー, Romanji: Faīrī) is a Clow Card with the power to control and manipulate fire. It is one of the four elemental cards, and as such it is one of the most powerful. Firey falls under the power of the Sun, Cerberus and Western Magic`,
    },
    {
      id: 5,
      title: 'the windy',
      category: 'wind',
      guardian: 'Yue - Moon',
      img: 'https://i.imgur.com/3xZabqi.jpeg',
      desc: `The Windy (Kanji: 風, Katakana: ウィンディー, Romanji: Uuindī) is a Clow Card with the power to create and control wind. It is one of the four elemental cards, and as such it is one of the most powerful. Windy falls under the power of the Moon, Yue and under Eastern Magic.`,
    },
    {
      id: 6,
      title: 'the earthy',
      category: 'earth',
      guardian: 'Kero - Sun',
      img: 'https://i.imgur.com/T7DqR79.jpeg',
      desc: `The Earthy (Kanji: 地, Katakana: アーシー, Romanji: Āshī) is a Clow Card with the power to control and manipulate earth. It is one of the four elemental cards, and as such it is one of the most powerful. Earthy falls under the power of the Sun, Cerberus and under Western Magic.`,
    },
    {
        id: 7,
        title: 'the change',
        category: 'dark',
        guardian: 'Yue - Moon',
        img: 'https://i.imgur.com/yTJgibz.jpeg',
        desc: `The Change (Kanji: 替, Katakana: チェーンジ, Romanji: Chēnji) is a Clow Card with the power to cause two people to switch bodies. It is under The Dark and under the power of the moon, Yue, and Eastern magic.`,
    },
      {
        id: 8,
        title: 'the illusion',
        category: 'dark',
        guardian: 'Yue - Moon',
        img: 'https://i.imgur.com/Jut3y6l.jpeg',
        desc: `The Illusion (Kanji: 幻, Katakana: イルージョン, Romanji: Irūjon) is a Clow Card with the power to create illusions. It is under The Dark and under the power of the Moon, Yue, and Eastern Magic.`,
      },
      {
        id: 9,
        title: 'the dream',
        category: 'dark',
        guardian: 'Yue - Moon',
        img: 'https://i.imgur.com/t6xNpAx.jpeg',
        desc: `The Dream (Kanji: 夢, Katakana: ドリーム, Romanji: Dorīmu) is a Clow Card with the power to manipulate dreams. It is under The Dark, the power of the Moon, Yue, and Eastern Magic.`,
      },
      {
        id: 10,
        title: 'the erase',
        category: 'dark',
        guardian: 'Yue - Moon',
        img: 'https://i.imgur.com/uwTRmqf.jpeg',
        desc: `The Erase (Kanji: 消, Katakana: エレーズ, Romanji: Erēzu) is a Clow Card with the power to erase anything from existence. It is under The Dark and under the power of the Moon, Yue, and Eastern Magic.`,
      },
      {
        id: 11,
        title: 'the silent',
        category: 'dark',
        guardian: 'Yue - Moon',
        img: 'https://i.imgur.com/3xZabqi.jpeg',
        desc: `The Silent (Kanji: 静, Katakana: サイレント, Romanji: Sairento) is a Clow Card with the power to manipulate silence. It is aligned under The Dark and under the power of the Moon, Yue, and Eastern Magic.`,
      },
      {
        id: 12,
        title: 'the sleep',
        category: 'dark',
        guardian: 'Yue - Moon',
        img: 'https://i.imgur.com/T7DqR79.jpeg',
        desc: `The Sleep (Kanji: 眠, Katakana: スリープ, Romanji: Surīpu) is a Clow Card with the power to put anyone to sleep. It is aligned under The Dark and under the power of the Moon, Yue, and Eastern Magic.`,
      },
      {
        id: 13,
        title: 'the time',
        category: 'dark',
        guardian: 'Yue - Moon',
        img: 'https://i.imgur.com/yTJgibz.jpeg',
        desc: `The Time (Kanji: 時, Katakana: タイム, Romanji: Taimu) is a Clow Card with the power to manipulate time. It is aligned under The Dark and under the power of the Moon, Yue, and Eastern Magic.`,
      },
      {
        id: 14,
        title: 'the big',
        category: 'light',
        guardian: 13.99,
        // img: './images/item-2.jpeg',
        img: 'https://i.imgur.com/Jut3y6l.jpeg',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
      },
      {
        id: 15,
        title: 'the create',
        category: 'water',
        guardian: 6.99,
        // img: './images/item-3.jpeg',
        img: 'https://i.imgur.com/t6xNpAx.jpeg',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
      },
      {
        id: 16,
        title: 'the glow',
        category: 'fire',
        guardian: 20.99,
        // img: './images/item-4.jpeg',
        img: 'https://i.imgur.com/uwTRmqf.jpeg',
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
      },
      {
        id: 17,
        title: 'the little',
        category: 'wind',
        guardian: 22.99,
        // img: './images/item-5.jpeg',
        img: 'https://i.imgur.com/3xZabqi.jpeg',
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
      },
      {
        id: 18,
        title: 'the return',
        category: 'earth',
        guardian: 18.99,
        // img: './images/item-6.jpeg',
        img: 'https://i.imgur.com/T7DqR79.jpeg',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
      },
  ];

  export default cards;